# Copyright © 2021 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Comprehensive tests for the base utility classes."""

import pytest

from notify_api.utils.base import BaseEnum, BaseMeta

# Test constants
HTTP_BAD_REQUEST = 400
HTTP_INTERNAL_SERVER_ERROR = 500


class SampleBaseEnum(BaseEnum):
    """Test enum using BaseEnum."""

    VALUE_ONE = "value_one"
    VALUE_TWO = "value_two"
    UPPER_CASE = "upper_case"


class TestAutoGeneratedEnum(BaseEnum):
    """Test enum with auto-generated values."""

    AUTO_VALUE_ONE = "auto_value_one"
    AUTO_VALUE_TWO = "auto_value_two"


class TestBaseMeta:
    """Test suite for BaseMeta class."""

    def test_contains_valid_value(self):
        """Test that __contains__ returns True for valid enum values."""
        assert "value_one" in SampleBaseEnum
        assert "value_two" in SampleBaseEnum
        assert "upper_case" in SampleBaseEnum

    def test_contains_invalid_value(self):
        """Test that __contains__ returns False for invalid enum values."""
        test_number = 123
        assert "invalid_value" not in SampleBaseEnum
        assert "VALUE_ONE" not in SampleBaseEnum  # Case sensitive
        assert "" not in SampleBaseEnum
        assert None not in SampleBaseEnum
        assert test_number not in SampleBaseEnum

    def test_contains_enum_member(self):
        """Test that __contains__ works with enum members."""
        assert SampleBaseEnum.VALUE_ONE in SampleBaseEnum
        assert SampleBaseEnum.VALUE_TWO in SampleBaseEnum

    def test_contains_edge_cases(self):
        """Test __contains__ with edge cases."""
        # Test with different types
        assert 0 not in SampleBaseEnum
        assert [] not in SampleBaseEnum
        assert {} not in SampleBaseEnum
        assert False not in SampleBaseEnum


class TestBaseEnumFunctionality:
    """Test suite for BaseEnum class."""

    def test_str_representation(self):
        """Test that __str__ returns the string value."""
        assert str(SampleBaseEnum.VALUE_ONE) == "value_one"
        assert str(SampleBaseEnum.VALUE_TWO) == "value_two"
        assert str(SampleBaseEnum.UPPER_CASE) == "upper_case"

    def test_enum_value_access(self):
        """Test accessing enum values."""
        assert SampleBaseEnum.VALUE_ONE.value == "value_one"
        assert SampleBaseEnum.VALUE_TWO.value == "value_two"
        assert SampleBaseEnum.UPPER_CASE.value == "upper_case"

    def test_get_enum_by_value_valid(self):
        """Test get_enum_by_value with valid values."""
        assert SampleBaseEnum.get_enum_by_value("value_one") == SampleBaseEnum.VALUE_ONE
        assert SampleBaseEnum.get_enum_by_value("value_two") == SampleBaseEnum.VALUE_TWO
        assert SampleBaseEnum.get_enum_by_value("upper_case") == SampleBaseEnum.UPPER_CASE

    def test_get_enum_by_value_invalid(self):
        """Test get_enum_by_value with invalid values."""
        assert SampleBaseEnum.get_enum_by_value("invalid_value") is None
        assert SampleBaseEnum.get_enum_by_value("VALUE_ONE") is None  # Case sensitive
        assert SampleBaseEnum.get_enum_by_value("") is None
        assert SampleBaseEnum.get_enum_by_value(None) is None

    def test_get_enum_by_value_edge_cases(self):
        """Test get_enum_by_value with edge cases."""
        test_number = 123
        assert SampleBaseEnum.get_enum_by_value(test_number) is None
        assert SampleBaseEnum.get_enum_by_value([]) is None
        assert SampleBaseEnum.get_enum_by_value({}) is None
        assert SampleBaseEnum.get_enum_by_value(False) is None

    def test_enum_iteration(self):
        """Test that enum can be iterated."""
        values = [enum_val for enum_val in SampleBaseEnum]
        expected_count = 3
        assert len(values) == expected_count
        assert SampleBaseEnum.VALUE_ONE in values
        assert SampleBaseEnum.VALUE_TWO in values
        assert SampleBaseEnum.UPPER_CASE in values

    def test_enum_equality(self):
        """Test enum equality comparisons."""
        assert SampleBaseEnum.VALUE_ONE == SampleBaseEnum.VALUE_ONE
        assert SampleBaseEnum.VALUE_ONE != SampleBaseEnum.VALUE_TWO
        assert SampleBaseEnum.VALUE_ONE == "value_one"
        assert SampleBaseEnum.VALUE_ONE != "value_two"

    def test_enum_membership(self):
        """Test enum membership using 'in' operator."""
        assert SampleBaseEnum.VALUE_ONE in SampleBaseEnum
        assert SampleBaseEnum.VALUE_TWO in SampleBaseEnum
        assert SampleBaseEnum.UPPER_CASE in SampleBaseEnum

    def test_generate_next_value_functionality(self):
        """Test the _generate_next_value_ static method functionality."""
        # This is tested implicitly through auto-generated enums
        result = SampleBaseEnum._generate_next_value_("TEST_NAME", 1, 1, [])
        assert result == "test_name"

        result = SampleBaseEnum._generate_next_value_("ANOTHER_TEST", 1, 1, [])
        assert result == "another_test"

        result = SampleBaseEnum._generate_next_value_("lowercase", 1, 1, [])
        assert result == "lowercase"

    def test_string_inheritance(self):
        """Test that BaseEnum inherits from str."""
        assert isinstance(SampleBaseEnum.VALUE_ONE, str)
        assert isinstance(SampleBaseEnum.VALUE_TWO, str)

        # Test string operations
        assert SampleBaseEnum.VALUE_ONE.upper() == "VALUE_ONE"
        assert SampleBaseEnum.VALUE_ONE.startswith("value")
        assert "one" in SampleBaseEnum.VALUE_ONE

    def test_enum_type_checking(self):
        """Test type checking and isinstance behavior."""
        assert isinstance(SampleBaseEnum.VALUE_ONE, SampleBaseEnum)
        assert isinstance(SampleBaseEnum.VALUE_ONE, str)
        assert isinstance(SampleBaseEnum.VALUE_ONE, SampleBaseEnum)

    def test_enum_comparison_with_strings(self):
        """Test comparison operations with strings."""
        assert SampleBaseEnum.VALUE_ONE == "value_one"
        assert SampleBaseEnum.VALUE_ONE != "value_two"
        assert SampleBaseEnum.VALUE_ONE < "value_two"  # String comparison
        assert SampleBaseEnum.VALUE_TWO > "value_one"

    def test_enum_hashing(self):
        """Test that enum values can be used as dictionary keys."""
        test_dict = {SampleBaseEnum.VALUE_ONE: "first", SampleBaseEnum.VALUE_TWO: "second"}

        assert test_dict[SampleBaseEnum.VALUE_ONE] == "first"
        assert test_dict[SampleBaseEnum.VALUE_TWO] == "second"

        # Test with string keys too
        string_dict = {"value_one": "first", "value_two": "second"}

        assert string_dict[SampleBaseEnum.VALUE_ONE] == "first"
        assert string_dict[SampleBaseEnum.VALUE_TWO] == "second"


class TestBaseEnumInheritanceAndIntegration:
    """Test suite for BaseEnum inheritance patterns and integration."""

    def test_multiple_enum_classes(self):
        """Test that multiple enum classes work independently."""
        assert SampleBaseEnum.VALUE_ONE != TestAutoGeneratedEnum.AUTO_VALUE_ONE
        assert "value_one" in SampleBaseEnum
        assert "auto_value_one" in TestAutoGeneratedEnum
        assert "value_one" not in TestAutoGeneratedEnum
        assert "auto_value_one" not in SampleBaseEnum

    def test_enum_with_complex_values(self):
        """Test enum with more complex scenarios."""

        class ComplexEnum(BaseEnum):
            SIMPLE = "simple"
            WITH_UNDERSCORE = "with_underscore"
            WITH_NUMBERS_123 = "with_numbers_123"
            SPECIAL_CHARS = "special-chars"

        assert ComplexEnum.SIMPLE == "simple"
        assert ComplexEnum.WITH_UNDERSCORE == "with_underscore"
        assert ComplexEnum.WITH_NUMBERS_123 == "with_numbers_123"
        assert ComplexEnum.SPECIAL_CHARS == "special-chars"

        assert "simple" in ComplexEnum
        assert "with_underscore" in ComplexEnum
        assert "with_numbers_123" in ComplexEnum
        assert "special-chars" in ComplexEnum

    def test_enum_edge_case_values(self):
        """Test enum with edge case values."""

        class EdgeCaseEnum(BaseEnum):
            EMPTY_STRING = ""
            SINGLE_CHAR = "a"
            LONG_VALUE = "a_very_long_enum_value_with_many_words_and_underscores"

        assert EdgeCaseEnum.EMPTY_STRING == ""
        assert EdgeCaseEnum.SINGLE_CHAR == "a"
        assert EdgeCaseEnum.LONG_VALUE == "a_very_long_enum_value_with_many_words_and_underscores"

        assert "" in EdgeCaseEnum
        assert "a" in EdgeCaseEnum
        assert "a_very_long_enum_value_with_many_words_and_underscores" in EdgeCaseEnum

    def test_enum_case_sensitivity(self):
        """Test that enum values are case sensitive."""

        class CaseSensitiveEnum(BaseEnum):
            lower_case = "lower_case"
            UPPER_CASE = "UPPER_CASE"
            Mixed_Case = "Mixed_Case"

        assert "lower_case" in CaseSensitiveEnum
        assert "UPPER_CASE" in CaseSensitiveEnum
        assert "Mixed_Case" in CaseSensitiveEnum

        assert "LOWER_CASE" not in CaseSensitiveEnum
        assert "upper_case" not in CaseSensitiveEnum
        assert "mixed_case" not in CaseSensitiveEnum

    def test_enum_duplicate_value_handling(self):
        """Test handling of enums with duplicate values."""

        class DuplicateEnum(BaseEnum):
            FIRST = "same_value"
            SECOND = "same_value"  # Duplicate value

        # Both should work, but they're aliases
        assert DuplicateEnum.FIRST == "same_value"
        assert DuplicateEnum.SECOND == "same_value"
        assert DuplicateEnum.FIRST is DuplicateEnum.SECOND  # They are the same object

        found_enum = DuplicateEnum.get_enum_by_value("same_value")
        assert found_enum == DuplicateEnum.FIRST
        assert found_enum == DuplicateEnum.SECOND

    def test_enum_with_none_value(self):
        """Test enum behavior with None as a value."""

        class NoneEnum(BaseEnum):
            NONE_VALUE = None
            STRING_VALUE = "string_value"

        # Since BaseEnum extends str, None gets converted to "None" string
        assert NoneEnum.NONE_VALUE == "None"
        assert NoneEnum.STRING_VALUE == "string_value"

        # Test membership
        assert "None" in NoneEnum  # None gets converted to "None" string
        assert "string_value" in NoneEnum
        assert "none" not in NoneEnum  # Case sensitive

    def test_get_enum_by_value_comprehensive(self):
        """Comprehensive test of get_enum_by_value method."""

        class ComprehensiveEnum(BaseEnum):
            ALPHA = "alpha"
            BETA = "beta"
            GAMMA = "gamma"

        # Valid cases
        assert ComprehensiveEnum.get_enum_by_value("alpha") == ComprehensiveEnum.ALPHA
        assert ComprehensiveEnum.get_enum_by_value("beta") == ComprehensiveEnum.BETA
        assert ComprehensiveEnum.get_enum_by_value("gamma") == ComprehensiveEnum.GAMMA

        # Invalid cases
        assert ComprehensiveEnum.get_enum_by_value("delta") is None
        assert ComprehensiveEnum.get_enum_by_value("ALPHA") is None
        assert ComprehensiveEnum.get_enum_by_value("") is None
        assert ComprehensiveEnum.get_enum_by_value(None) is None
        assert ComprehensiveEnum.get_enum_by_value(123) is None
        assert ComprehensiveEnum.get_enum_by_value([]) is None
        assert ComprehensiveEnum.get_enum_by_value({}) is None


class TestUtilityMissingCoverage:
    """Test class for utility missing coverage."""

    def test_download_file_success(self):
        """Test download_file function success."""
        from unittest.mock import MagicMock, patch

        from notify_api.utils.util import download_file

        test_url = "https://example.com/test.pdf"
        test_content = b"test file content"

        with patch("urllib.request.urlopen") as mock_urlopen:
            mock_response = MagicMock()
            mock_response.read.return_value = test_content
            mock_response.__enter__ = lambda self: mock_response
            mock_response.__exit__ = lambda self, *args: None
            mock_urlopen.return_value = mock_response

            result = download_file(test_url)

            assert result == test_content
            mock_urlopen.assert_called_once_with(test_url)
            mock_response.read.assert_called_once()

    def test_download_file_http_error(self):
        """Test download_file function with HTTP error."""
        from unittest.mock import patch
        from urllib.error import URLError

        from notify_api.utils.util import download_file

        test_url = "https://example.com/notfound.pdf"

        with patch("urllib.request.urlopen") as mock_urlopen:
            mock_urlopen.side_effect = URLError("HTTP Error 404: Not Found")

            with pytest.raises(URLError, match="HTTP Error 404: Not Found"):
                download_file(test_url)

            mock_urlopen.assert_called_once_with(test_url)

    def test_download_file_timeout_error(self):
        """Test download_file function with timeout error."""
        from unittest.mock import patch
        from urllib.error import URLError

        from notify_api.utils.util import download_file

        test_url = "https://example.com/slow.pdf"

        with patch("urllib.request.urlopen") as mock_urlopen:
            mock_urlopen.side_effect = URLError("timeout")

            with pytest.raises(URLError, match="timeout"):
                download_file(test_url)

            mock_urlopen.assert_called_once_with(test_url)

    def test_to_camel_function_usage(self):
        """Test to_camel function usage."""
        from notify_api.utils.util import to_camel

        # Test snake_case to camelCase conversion
        assert to_camel("snake_case") == "snakeCase"
        assert to_camel("test_field_name") == "testFieldName"
        assert to_camel("single") == "single"
        assert to_camel("already_camelcase") == "alreadyCamelcase"

        # Test with underscores at start/end
        assert to_camel("_private_field") == "_private_field"
        assert to_camel("field_name_") == "fieldName"


class TestConfigMissingCoverage:
    """Test class for config missing coverage."""

    def test_config_database_url_construction(self):
        """Test database URL construction in config."""
        import os
        from unittest.mock import patch

        # Test that the config class variables are accessible
        # Since Config class variables are evaluated at import time,
        # we test that the attribute exists and is a string
        from notify_api.config import Config

        config = Config()

        # Test that SQLALCHEMY_DATABASE_URI is accessible and is a string
        assert hasattr(config, "SQLALCHEMY_DATABASE_URI")
        assert isinstance(config.SQLALCHEMY_DATABASE_URI, str)
        assert "postgresql+pg8000" in config.SQLALCHEMY_DATABASE_URI

    def test_config_testing_environment(self):
        """Test config in testing environment."""
        from notify_api.config import UnitTestingConfig

        config = UnitTestingConfig()

        # Test testing-specific configurations
        assert config.TESTING is True
        assert "postgresql+pg8000" in config.SQLALCHEMY_DATABASE_URI

    def test_config_production_settings(self):
        """Test config production settings."""
        from notify_api.config import ProductionConfig

        config = ProductionConfig()

        assert config.DEBUG is False
        # Test that SQLALCHEMY_DATABASE_URI exists and contains the expected driver
        assert hasattr(config, "SQLALCHEMY_DATABASE_URI")
        assert isinstance(config.SQLALCHEMY_DATABASE_URI, str)
        assert "postgresql+pg8000" in config.SQLALCHEMY_DATABASE_URI
        assert config.DEVELOPMENT is False

    def test_error_handler_business_exception(self):
        """Test error handler for business exceptions."""
        from flask import Flask

        from notify_api.exceptions.errorhandlers import ExceptionHandler

        app = Flask(__name__)
        exception_handler = ExceptionHandler(app)

        # Test that exception handler is properly initialized
        assert exception_handler.app == app

    def test_error_handler_validation_error(self, app):
        """Test error handler for validation errors."""
        from unittest.mock import Mock

        from notify_api.exceptions.errorhandlers import ExceptionHandler

        # Mock a validation error
        mock_error = Mock()
        mock_error.body_params = [{"msg": "field required"}]

        handler = ExceptionHandler()

        with app.app_context():
            response, status_code, headers = handler.validation_handler(mock_error)

        assert status_code == HTTP_BAD_REQUEST
        assert "error" in response.get_json()
        assert response.get_json()["error"] == "field required"

    def test_error_handler_default_exception_handler(self, app):
        """Test default exception handler."""
        from unittest.mock import Mock, patch

        from notify_api.exceptions.errorhandlers import ExceptionHandler

        handler = ExceptionHandler()

        # Test with Exception
        test_exception = Exception("Test error message")

        with app.test_request_context():
            response, status_code, headers = handler.std_handler(test_exception)

        assert status_code == HTTP_INTERNAL_SERVER_ERROR
        assert "message" in response
        assert response["message"] == "Internal server error"

    def test_error_handler_business_exception_handler(self, app):
        """Test business exception handler."""
        from notify_api.exceptions.errorhandlers import ExceptionHandler

        handler = ExceptionHandler()
        business_error = ValueError("Business logic error")

        with app.test_request_context():
            response, status_code, headers = handler.std_handler(business_error)

        assert status_code == HTTP_INTERNAL_SERVER_ERROR
        assert "message" in response
        assert response["message"] == "Internal server error"

    def test_version_endpoint_ops_healthz(self):
        """Test version endpoint initialization."""
        from notify_api.resources.constants import EndpointVersionPath
        from notify_api.resources.version_endpoint import VersionEndpoint

        # Create a version endpoint instance
        version_endpoint = VersionEndpoint("test", EndpointVersionPath.API_V1, [])

        assert version_endpoint.version_bp is not None
        assert version_endpoint.version_bp.name == "test"

    def test_version_endpoint_ops_readyz(self):
        """Test version endpoint with app initialization."""
        from unittest.mock import Mock

        from notify_api.resources.constants import EndpointVersionPath
        from notify_api.resources.version_endpoint import VersionEndpoint

        # Create a mock Flask app
        mock_app = Mock()
        mock_app.register_blueprint = Mock()

        # Create a version endpoint instance and initialize it
        version_endpoint = VersionEndpoint("test", EndpointVersionPath.API_V1, [])
        version_endpoint.init_app(mock_app)

        assert version_endpoint.app == mock_app
        mock_app.register_blueprint.assert_called_once_with(version_endpoint.version_bp)

    def test_version_endpoint_initialization(self):
        """Test version endpoint blueprint initialization with exception."""
        from notify_api.resources.constants import EndpointVersionPath
        from notify_api.resources.version_endpoint import VersionEndpoint

        # Test initialization without Flask app
        version_endpoint = VersionEndpoint("test", EndpointVersionPath.API_V1, [])

        # Test exception when trying to initialize with None app
        try:
            version_endpoint.init_app(None)
            raise AssertionError("Should have raised an exception")
        except Exception as e:
            assert "Cannot initialize without a Flask App" in str(e)

    def test_meta_endpoint_info(self, app):
        """Test meta endpoint info method."""
        from notify_api.resources.meta.meta import info

        with app.app_context():
            response = info()

            assert response is not None
            # Response should contain API information
            response_data = response.get_json()
            assert "API" in response_data
            assert "FrameWork" in response_data
            assert "notify_api" in response_data["API"]
