"""add notification_id to history

Revision ID: 5b8087f8b7e3
Revises: 328095fcc390
Create Date: 2026-02-06 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8087f8b7e3'
down_revision = '328095fcc390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('notification_history', sa.Column('notification_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notification_history_notification_id'), 'notification_history', ['notification_id'], unique=False)
    # Note: No foreign key constraint - notification records are deleted after history is created
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index(op.f('ix_notification_history_notification_id'), table_name='notification_history')
    op.drop_column('notification_history', 'notification_id')
    # ### end Alembic commands ###
