"""0007_scanning_date

Revision ID: 082123afb70c
Revises: 62d200ebcba9
Create Date: 2024-12-19 16:15:19.656177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '082123afb70c'
down_revision = '62d200ebcba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_scanning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_ts', sa.DateTime(), nullable=True))
        batch_op.alter_column('scan_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_document_scanning_create_ts'), ['create_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_scanning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_scanning_create_ts'))
        batch_op.alter_column('scan_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('create_ts')

    # ### end Alembic commands ###
