"""0012_filing_type

Revision ID: 2fec8063267e
Revises: f83ffefd82b7
Create Date: 2025-11-26 08:59:08.706933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fec8063267e'
down_revision = 'f83ffefd82b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    filing_types = op.create_table('filing_type_documents',
    sa.Column('filing_type', sa.String(length=30), nullable=False),
    sa.Column('document_type', postgresql.ENUM('REG_101', 'REG_102', 'REG_103', 'ABAN', 'ADDI', 'AFFE', 'ATTA', 'BANK', 'BCLC', 'CAU', 'CAUC', 'CAUE', 'COMP', 'COUR', 'DEAT', 'DNCH', 'EXMN', 'EXNR', 'EXRE', 'EXRS', 'FORE', 'FZE', 'GENT', 'LETA', 'MAID', 'MAIL', 'MARR', 'NAMV', 'NCAN', 'NCON', 'NPUB', 'NRED', 'PDEC', 'PUBA', 'REBU', 'REGC', 'REIV', 'REPV', 'REST', 'STAT', 'SZL', 'TAXN', 'TAXS', 'THAW', 'TRAN', 'VEST', 'WHAL', 'WILL', 'XP_MISC', 'COFI', 'DISS', 'DISD', 'ATTN', 'FRMA', 'AMLO', 'CNTA', 'CNTI', 'CNTO', 'COFF', 'COSD', 'AMLG', 'AMAL', 'RSRI', 'ASNU', 'LPRG', 'FILE', 'CNVF', 'COPN', 'MHSP', 'FNCH', 'CONS', 'PPRS', 'PPRC', 'ADDR', 'ANNR', 'CORR', 'DIRS', 'CORC', 'SOCF', 'CERT', 'LTR', 'CLW', 'BYLW', 'CNST', 'CONT', 'SYSR', 'ADMN', 'RSLN', 'AFDV', 'SUPP', 'MNOR', 'FINM', 'APCO', 'RPTP', 'DAT', 'BYLT', 'CNVS', 'CRTO', 'MEM', 'PRE', 'REGO', 'PLNA', 'REGN', 'FINC', 'BCGT', 'CHNM', 'OTP', 'PPR', 'LHS', 'RGS', 'HSR', 'RPL', 'FINS', 'DELETED', 'COOP_RULES', 'COOP_MEMORANDUM', 'CORP_AFFIDAVIT', 'DIRECTOR_AFFIDAVIT', 'PART', 'REG_103E', 'AMEND_PERMIT', 'CANCEL_PERMIT', 'REREGISTER_C', 'MEAM', 'COU', 'CRT', 'INV', 'NATB', 'NWP', 'APP_FILE', 'FZE_ADMIN', 'AGMEX', 'AGMLC', 'NOALA', 'AGMAM', 'RECV_APPOINT', 'RECV_CEASE', 'CHANGE_NAME', 'CHANGE_OFF', 'CHANGE_REG', 'CNV_LEDGER', 'CRTO_LIQ', 'DISS_VOL', 'DISS_ADMIN', 'ICORP', 'INTENT_LIQ', 'OTHER_LEGACY', 'NWITH', 'PB_OFF', 'PB_ON', 'REG_BUS', 'RSLN_SPEC', 'TRANSITION', 'TRANSP_REG', name='documenttype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['document_type'], ['document_types.document_type'], ),
    sa.PrimaryKeyConstraint('filing_type', 'document_type')
    )
    with op.batch_alter_table('filing_type_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_type_documents_document_type'), ['document_type'], unique=False)

    # Manually added begin
    op.bulk_insert(
        filing_types,
        [
            {"filing_type": "adminFreeze", "document_type": "FZE_ADMIN"},
            {"filing_type": "agmExtension", "document_type": "AGMEX"},
            {"filing_type": "agmLocationChange", "document_type": "AGMLC"},
            {"filing_type": "alteration", "document_type": "NOALA"},
            {"filing_type": "amalgamationApplication", "document_type": "AMLG"},
            {"filing_type": "amalgamationOut", "document_type": "AMLO"},
            {"filing_type": "amendedAGM", "document_type": "AGMAM"},
            {"filing_type": "amendedAnnualReport", "document_type": "ANNR"},
            {"filing_type": "amendedChangeOfDirectors", "document_type": "DIRS"},
            {"filing_type": "annualReport", "document_type": "ANNR"},
            {"filing_type": "appointLiquidator", "document_type": "FILE"},
            {"filing_type": "appointReceiver", "document_type": "RECV_APPOINT"},
            {"filing_type": "ceaseLiquidator", "document_type": "FILE"},
            {"filing_type": "ceaseReceiver", "document_type": "RECV_CEASE"},
            {"filing_type": "changeLiquidatorAddress", "document_type": "FILE"},
            {"filing_type": "changeOfAddress", "document_type": "ADDR"},
            {"filing_type": "changeOfDirectors", "document_type": "DIRS"},
            {"filing_type": "changeOfName", "document_type": "CHANGE_NAME"},
            {"filing_type": "changeOfOfficers", "document_type": "CHANGE_OFF"},
            {"filing_type": "changeOfRegistration", "document_type": "CHANGE_REG"},
            {"filing_type": "changeRespectingDCR", "document_type": "FILE"},
            {"filing_type": "consentAmalgamationOut", "document_type": "CONT"},
            {"filing_type": "consentContinuationOut", "document_type": "CONT"},
            {"filing_type": "continuationIn", "document_type": "CNTI"},
            {"filing_type": "continuationOut", "document_type": "CNTO"},
            {"filing_type": "conversion", "document_type": "CNVS"},
            {"filing_type": "conversionLedger", "document_type": "CNV_LEDGER"},
            {"filing_type": "correction", "document_type": "CORC"},
            {"filing_type": "courtOrder", "document_type": "CRTO"},
            {"filing_type": "delayOfDissolution", "document_type": "DISD"},
            {"filing_type": "dissolution", "document_type": "DISS_ADMIN"},
            {"filing_type": "incorporationApplication", "document_type": "ICORP"},
            {"filing_type": "intentToLiquidate", "document_type": "INTENT_LIQ"},
            {"filing_type": "involuntaryDissolution", "document_type": "DISS_ADMIN"},
            {"filing_type": "legacyOther", "document_type": "OTHER_LEGACY"},
            {"filing_type": "locationDCR", "document_type": "FILE"},
            {"filing_type": "noticeOfWithdrawal", "document_type": "NWITH"},
            {"filing_type": "putBackOff", "document_type": "PB_OFF"},
            {"filing_type": "putBackOn", "document_type": "PB_ON"},
            {"filing_type": "registrarsNotation", "document_type": "REGN"},
            {"filing_type": "registrarsOrder", "document_type": "REGO"},
            {"filing_type": "registration", "document_type": "REG_BUS"},
            {"filing_type": "restoration", "document_type": "RSRI"},
            {"filing_type": "restorationApplication", "document_type": "RSRI"},
            {"filing_type": "specialResolution", "document_type": "RSLN_SPEC"},
            {"filing_type": "transferRecordsOffice", "document_type": "FILE"},
            {"filing_type": "transition", "document_type": "TRANSITION"},
            {"filing_type": "transparencyRegister", "document_type": "TRANSP_REG"},
            {"filing_type": "voluntaryDissolution", "document_type": "DISS_VOL"},
            {"filing_type": "voluntaryLiquidation", "document_type": "FILE"},
        ],
    )
    # Manually added end

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filing_type_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filing_type_documents_document_type'))

    op.drop_table('filing_type_documents')
    # ### end Alembic commands ###
