"""0008_consumer_reference_id

Revision ID: c85dfd9fdcb2
Revises: 082123afb70c
Create Date: 2025-01-20 11:29:06.245335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85dfd9fdcb2'
down_revision = '082123afb70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumer_reference_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('consumer_reference_id')

    # ### end Alembic commands ###
