"""0004_scanning_app

Revision ID: d41256aa4367
Revises: 43a86e041c8a
Create Date: 2024-09-24 14:06:35.776692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence  # Added manually.


# revision identifiers, used by Alembic.
revision = 'd41256aa4367'
down_revision = '43a86e041c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### Manually create sequences and add them to pk columns. ###
    op.execute(CreateSequence(Sequence('scanning_author_id_seq', start=1, increment=1)))
    op.execute(CreateSequence(Sequence('scanning_box_id_seq', start=1, increment=1)))
    op.execute(CreateSequence(Sequence('scanning_parameter_id_seq', start=1, increment=1)))
    op.execute(CreateSequence(Sequence('scanning_schedule_id_seq', start=1, increment=1)))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanning_authors',
    sa.Column('id', sa.Integer(), sa.Sequence('scanning_author_id_seq'), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanning_boxes',
    sa.Column('id', sa.Integer(), sa.Sequence('scanning_box_id_seq'), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('schedule_number', sa.Integer(), nullable=False),
    sa.Column('box_number', sa.Integer(), nullable=False),
    sa.Column('opened_date', sa.DateTime(), nullable=True),
    sa.Column('closed_date', sa.DateTime(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanning_parameters',
    sa.Column('id', sa.Integer(), sa.Sequence('scanning_parameter_id_seq'), nullable=False),
    sa.Column('use_document_feeder', sa.Boolean(), nullable=True),
    sa.Column('show_twain_ui', sa.Boolean(), nullable=True),
    sa.Column('show_twain_progress', sa.Boolean(), nullable=True),
    sa.Column('use_full_duplex', sa.Boolean(), nullable=True),
    sa.Column('use_low_resolution', sa.Boolean(), nullable=True),
    sa.Column('max_pages_in_box', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanning_schedules',
    sa.Column('id', sa.Integer(), sa.Sequence('scanning_schedule_id_seq'), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('schedule_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('scanning_schedules')
    op.drop_table('scanning_parameters')
    op.drop_table('scanning_boxes')
    op.drop_table('scanning_authors')

    # Manually added drop sequence commands ###
    op.execute(DropSequence(Sequence('scanning_author_id_seq')))
    op.execute(DropSequence(Sequence('scanning_box_id_seq')))
    op.execute(DropSequence(Sequence('scanning_parameter_id_seq')))
    op.execute(DropSequence(Sequence('scanning_schedule_id_seq')))

    # ### end Alembic commands ###
