"""0011_event_tracking

Revision ID: f83ffefd82b7
Revises: 3d920eadcbdf
Create Date: 2025-06-13 15:28:52.261326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence  # Added manually.


# revision identifiers, used by Alembic.
revision = 'f83ffefd82b7'
down_revision = '3d920eadcbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### Manually create sequences and add them to pk columns. ###
    op.execute(CreateSequence(Sequence('event_tracking_id_seq', start=1, increment=1)))

    # ### commands auto generated by Alembic - please adjust! ###
    event_tracking_type = op.create_table('event_tracking_types',
    sa.Column('event_tracking_type', sa.String(length=20), nullable=False),
    sa.Column('event_tracking_desc', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('event_tracking_type')
    )
    op.create_table('event_tracking',
    sa.Column('id', sa.Integer(), sa.Sequence('event_tracking_id_seq'), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('event_ts', sa.DateTime(), nullable=False),
    sa.Column('event_tracking_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('email_address', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['event_tracking_type'], ['event_tracking_types.event_tracking_type'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_tracking_event_tracking_type'), ['event_tracking_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_tracking_event_ts'), ['event_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_tracking_key_id'), ['key_id'], unique=False)

    # ### Manually add type table insert statements. ###
    op.bulk_insert(event_tracking_type,
      [
        { 'event_tracking_type': 'PDF_CONVERT', 'event_tracking_desc': 'Convert a document to PDF.' },
        { 'event_tracking_type': 'PDF_CLEAN', 'event_tracking_desc': 'Clean/sanitize a PDF document.' },
        { 'event_tracking_type': 'DOC_PAYMENT', 'event_tracking_desc': 'Document form payment status (credit card).' }
      ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_tracking_key_id'))
        batch_op.drop_index(batch_op.f('ix_event_tracking_event_ts'))
        batch_op.drop_index(batch_op.f('ix_event_tracking_event_tracking_type'))

    op.drop_table('event_tracking')
    op.drop_table('event_tracking_types')

    # Manually added drop sequence commands ###
    op.execute(DropSequence(Sequence('event_tracking_id_seq')))
    # ### end Alembic commands ###
